#+TITLE: Readme
#+OPTIONS: toc:nil

* A file manager inspired by NetRW on Vim

* Installation
Clone it by doing =git clone https://github.com/Bowuigi/Vex=

To build it, use =make=

To install it, use =sudo make install=

To put a desktop file on every user's desktop, use =make desktop=

* Features
+ Open files your editor of choice (changed at compile time)
+ Delete files (press `d` and then `y` on the file you want to delete)
+ Browse through files
+ Compatible with transparency
+ Tiny
+ That is it, it is a small project

* Planned features
+ Execute binary files
+ Basic operations (cut, copy, paste, rename, creating files and folders, etc.)
+ A rewrite (in progress, this org document is the first part), this will result in:
  * Better performance
  * Better ways to configure keybindings
  * Better codebase
  * Logging functions, for easier error handling and communication with the user.
+ Better messages for easier readability
+ Better small screen support
+ Searching, this will drastically improve usage speed, but will be hard to implement with a decent performance.

* Progress on the planned features
+ Rewrite: currently going, I am still thinking on how will the include chain be.
+ Better small screen support: The loginfo() function included in the rewrite has support for small screens, most of the stuff on the application window is truncated when the screen is too small.
+ Searching: A demo on a program that searches stdin with a good performance was made and tested. The feature will be implemented as soon as the rewrite is finished.
+ Basic operations: Concepts have been made, will be implemented after searching.
+ Executing binary files: still in a thinking process, probably stopping curses during the program execution and asking for confirmation before opening it again.
